title: Rakshit Soral
url: "https://rakshitsoral.ga"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname: rakshitsoral1

# Default description in social shares for the jekyll-seo-tag gem
description: Rakshit Soral is a Digital Marketer, conversion strategist and seasoned web developer. Read his blog or contact him via Email.

# Author details for the jekyll-seo-tag gem
author:
  name: Rakshit Soral
  email: rakshitsoral@gmail.com
  twitter: RakshitSoral # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Rakshit Soral
  links:
    - https://github.com/CloudCannon/urban-jekyll-template

timezone: Etc/UTC

collections:
  staff_members:
    output: false
  insights:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "insights"
    values:
      layout: "insight"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

  ############################################################
# Site configuration for the WebP Generator Plugin
# The values here represent the defaults if nothing is set
webp:
  enabled: true

  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize
  # Nested directories will not be checked
  img_dir: ["/images"]

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files 
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: true

  # Path to the WebP utilities to use (relative or absolute)
  webp_path: "_plugins/webp/x64"

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # List of files or directories to explicitly include 
  # e.g. single files outside of the main image directories
  include: []
############################################################